apiVersion: apps/v1
kind: Deployment
metadata:
  name: uloe
spec:
  replicas: 5
  selector:
    matchLabels:
      app: uloe
  template:
    metadata:
      labels:
        app: uloe
    spec:
      containers:
      - name: uloe-server
        image: rakeshkoru91/uloe-server:0.1.0
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: added-items-log
          mountPath: /usr/src/app/added_items.log
          subPath: added_items.log
          readOnly: false
        ports:
        - name: web
          containerPort: 3001
          protocol: TCP
        env:
        - name: MONGODB_HOST
          valueFrom:
            configMapKeyRef:
              name: uloe-config
              key: mongodb.host
        - name: MONGODB_PORT
          valueFrom:
            configMapKeyRef:
              name: uloe-config
              key: mongodb.port
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: uloe-secure-config
              key: mongodb.username
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: uloe-secure-config
              key: mongodb.password
      - name: uloe-frontend
        image: rakeshkoru91/uloe-frontend:0.1.0
        ports:
        - name: web
          containerPort: 5000
          protocol: TCP
        volumeMounts:
        - name: frontend-config
          mountPath: /usr/src/app/.env
          subPath: .env
          readOnly: true
      volumes:
      - name: added-items-log
        emptyDir: {}
      - name: frontend-config
        configMap:
          name: uloe-config
          items:
          - key: .env
            path: .env
