apiVersion: v1
kind: Service
metadata:
  name: uloe-svc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5020
      nodePort: 30050
      protocol: TCP
      name: frontend
    - protocol: TCP
      port: 30051
      nodePort: 30051
      targetPort: 3030
      name: server
  selector:
    app: uloe
